= penlog(7)
:doctype:    manpage
:man source: penlog

== Name

penlog - A generic and machine readable logging format

== Specification

The PENLog logging format is intended to be used as a generic and reusable data format for measurement data.
The specification contains a machine readable format in JSON for post-processing and digital archiving.
The tool `hr(1)` is intended to be used -- similar to `cat(1)` -- for viewing the JSON data.
The format which is generated by the `hr(1)` tool is called "human readable format".

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here.

=== JSON Format

Unset fields which are considered optional MUST be absent in the JSON data.
Unset fields which are considered required MUST be set to its zero value (string: `""`, int: `0`, bool: `false`).
The JSON format consists of the following fields:

`component` (string, OPTIONAL)::
    The component, e.g. software module, which has issued the log message.
    In absence, an implementation SHOULD pull the content of the environment variable `PENLOG_COMPONENT` and MUST set it to `root` as a fallback.

`data` (string, REQUIRED)::
    The log message as an UTF-8 string.

`host` (string, OPTIONAL)::
    The hostname of the machine who generated the messages.
    This field is OPTIONAL, since it is missing in the human readable format.
    It is RECOMMENDED that implementations include this field, as it increases reproducability of logging data.

`line` (string, OPTIONAL)::
    Information about the file and line number where this log entry was generated.
    The information MUST be in the form `filename:number`.
    `filename` can be an absolute or relative path, or a filename.

`priority` (int, OPTIONAL)::
    This field can be used to optionally set the priority.
    For priorities, the syslog priorities are used as defined by RFC5424.
    Implementations can indicate priorities by e.g. a separate color.

`stacktrace` (string, OPTIONAL)::
    Implementations can optionally include a stacktrace.
    This could be useful for debugging if fatal errors occur.
    Stacktraces are very specific to the used programming language, e.g. python or go.
    Thus, this field is just an unstructured string.

`tags` (list[string], OPTIONAL)::
    To each log entry a custom list of tags can be applied.
    For instance: `["autogenerated", "pre-test", "post-test", …]`.

`timestamp` (string, REQUIRED)::
    ISO8601 string of the current date.

`type` (string, REQUIRED)::
    The type field is a free field which can be used to assign a particular message type.

Custom fields can be added freely, in other words, additional custom fields are OPTIONAL.
Their post-processing and tooling around these custom fields is up to the developer and MUST be ignored by generic converters.

A penlog log file consists of a verbatim sequence of the described JSON objects.
Each JSON object MUST be present at one line, separated by `\n` (ascii 0x0a).
In order to keep decoding simple and line based, no JSON arrays or virtual, endless JSON structures are employed.

Example (prettified for readability reasons):

    {
      "timestamp": "2020-04-02T12:48:08.906523",
      "component": "scanner",
      "type": "msg",
      "data": "Starting tshark",
      "host": "kronos"
    }
    {
      "timestamp": "2020-04-02T12:48:09.583521",
      "component": "moncay",
      "type": "msg",
      "data": "Doing stuff",
      "host": "kronos"
    }

If encoding of a log message fails, the component MUST be set to `JSON`, the type to `ERROR`, and the error message MUST be included in `data`.

=== Human Readable Format

The syntax of the human readable format looks like the following.
Curly braces indicate a field from the JSON format.
If a field is empty it expands to an zero length string.
A verbatim curly brace brace is expressed with two ones: `{{` means `{`.

    {timestamp} {{{component}}} [{type}]: {data} ({line})

`timestamp`::
    The RECOMMENDED timestamp format is Go's `StampMilli` format as defined to `Jan _2 15:04:05.000`.

`component`::
`type`::
    The `component` and `type` fields MUST be padded or truncated that the colons, `:`, in every single line are perfectly aligned.
    For small projects only consisting of a single component, the `component` field MAY be omitted.

`data`::
    The actual log message.
    It MAY be truncated to fit in the current terminal size.
    When it is truncated an ellipsis character (`…`) MUST be appended to indicate the truncation for the user,

`line`::
    The optional filename and line number where this log entry origins from.

=== Example

    Apr  2 12:48:08.906 {scanner } [msg   ]: Starting tshark with
    Apr  2 12:48:09.583 {moncay  } [msg   ]: Doing stuff

If a JSON line cannot be decoded, the faulty text MUST be included in messages of type `ERROR` and component `JSON`:

    $ python -c "import foo" 2>&1 | hr
    Jun 16 08:19:01.305 {JSON    } [ERROR   ]: Traceback (most recent call last):
    Jun 16 08:19:01.305 {JSON    } [ERROR   ]:   File "<string>", line 1, in <module>
    Jun 16 08:19:01.305 {JSON    } [ERROR   ]: ModuleNotFoundError: No module named 'foo'

== Environment Variables

The following environment variables MAY be understood by penlog implementations.
The supported datatypes are `string` and `bool`.
A `bool` is a special string consisting of either `t, T, true, TRUE, 1` or `f, F, false, FALSE, 0`.

`PENLOG_COMPONENT` (string)::
    If no component is set, the `component` field MAY be set via the `PENLOG_COMPONENT` variable at the scope of an operating system process.

`PENLOG_FORCE_COLORS` (bool)::
    It is best practice to disable color escape codes when the relevant output streams are redirected to a file or a pipe.
    Setting thes evironmental variable enforces color escape codes.

`PENLOG_LINES` (bool)::
    If this environment variable is set, implementations SHOULD emit filenames with line numbers via the `line` field.

`PENLOG_SHOW_LINES` bool::
    A switch for implementations which output the human readable form.
    The display of line numbers can be enabled or disabled with this variable.

== See Also

hr(1), penlog-best-practice(7)

include::footer.adoc[]
