= penlog(7)
:doctype:    manpage
:man source: penlog

== Name

penlog - A generic logging format v1

== Specification

The PENLog logging format is intended to be used as a generic and reusable data format for measurement data.
The specification contains a machine readable format in JSON for post-processing and digital archiving.
The tool `hr(1)` is intended to be used -- similar to `cat(1)` -- for viewing the JSON data.
The format which is generated by the `hr(1)` tool is called "human readable format".

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here.

=== JSON Format

Unset fields which are considered optional MUST be absent in the JSON data.
Unset fields which are considered required MUST be set to its zero value (string: `""`, int: `0`, bool: `false`).
The JSON format consists of the following fields:

`component` (string, OPTIONAL)::
    The component, e.g. software module, which has issued the log message.
    In absence, an implementation SHOULD pull the content of the environment variable `PENLOG_COMPONENT` and MUST set it to `root` as a fallback.

`data` (string, REQUIRED)::
    The log message as an UTF-8 string.

`host` (string, OPTIONAL)::
    The hostname of the machine who generated the messages.
    This field is OPTIONAL, since it is missing in the human readable format.
    It is RECOMMENDED that implementations include this field, as it increases reproducability of logging data.

`line` (string, OPTIONAL)::
    Information about the file and line number where this log entry was generated.
    The information MUST be in the form `filename:number`.
    `filename` can be an absolute or relative path, or a filename.

`tags` (list[string], OPTIONAL)::
    To each log entry a custom list of tags can be applied.
    For instance: `["autogenerated", "pre-test", "post-test", …]`.

`timestamp` (string, REQUIRED)::
    ISO8601 string of the current date.

`type` (string, REQUIRED)::
    The type field is a free field which can be used to assign a particular message type.

Custom fields can be added freely, in other words, additional custom fields are OPTIONAL.
Their post-processing and tooling around these custom fields is up to the developer and MUST be ignored by generic converters.

A penlog log file consists of a verbatim sequence of the described JSON objects.
Each JSON object MUST be present at one line, separated by `\n` (ascii 0x0a).
In order to keep decoding simple and line based, no JSON arrays or virtual, endless JSON structures are employed.

Example (prettified for readability reasons):

    {
      "timestamp": "2020-04-02T12:48:08.906523",
      "component": "scanner",
      "type": "msg",
      "data": "Starting tshark",
      "host": "kronos"
    }
    {
      "timestamp": "2020-04-02T12:48:09.583521",
      "component": "moncay",
      "type": "msg",
      "data": "Doing stuff",
      "host": "kronos"
    }

If encoding of a log message fails, the component MUST be set to `JSON`, the type to `ERROR`, and the error message MUST be included in `data`.

=== Human Readable Format

The syntax of the human readable format looks like the following.
Curly braces indicate a field from the JSON format.
If a field is empty it expands to an zero length string.
A verbatim curly brace brace is expressed with two ones: `{{` means `{`.

    {timestamp} {{{component}}} [{type}]: {data} ({line})

`timestamp`::
    The RECOMMENDED timestamp format is Go's `StampMilli` format as defined to `Jan _2 15:04:05.000`.

`component`::
`type`::
    The `component` and `type` fields MUST be padded or truncated that the colons, `:`, in every single line are perfectly aligned.
    For small projects only consisting of a single component, the `component` field MAY be omitted.

`line`::
    The optional filename and line number where this log entry origins from.

`data`::
    The actual log message.
    It MAY be truncated to fit in the current terminal size.
    When it is truncated an ellipsis character (`…`) MUST be appended to indicate the truncation for the user,

Example:

    Apr  2 12:48:08.906 {scanner } [msg   ]: Starting tshark with
    Apr  2 12:48:09.583 {moncay  } [msg   ]: Doing stuff

If a JSON line cannot be decoded it MUST be prefixed with `error:␣` (␣ is a blank space, ascii 0x20) and included in the output:

    $ python -c "import foo" 2>&1 | hr
    error: Traceback (most recent call last):
    error:   File "<string>", line 1, in <module>
    error: ModuleNotFoundError: No module named 'foo'

== License

This document is published under the Apache-2.0 license.

== Authors

Current maintainers are:

* Stefan Tatschner <stefan@rumpelsepp.org>
* Tobias Specht

== Bugs

This project is maintained on Github: https://github.com/Fraunhofer-AISEC/penlog.

== See Also

hr(1)
