= penrun(1)
:doctype:    manpage
:man source: penlog

== Name

pendump - A configurable runner for commands which create artifacts

== Synopsis

----
penrun [ARGS] SHELLCOMMAND…
----

== Description

penrun(1) is a runner intended for invoking measurements; any shellcommand can be started.
A well defined directory structure is created for the so called "artifacts".
SHELLCOMMAND is run within this directory which is there for any results (e.g. pcap files, penlog artifacts, …).
For more information about the artifacts directory, see the ARTIFACTS section.

== Customization
=== Config Files

Customization is possible with config files, which are plain boring bash files.
The following locations are searched in this order.
The filepath of each config is exported as an environment variable.

* `PENRUN_PWD_CONF`: `$PWD/.penrun.sh`
* `PENRUN_GIT_ROOT_CONF`: `$GITROOT/.penrun.sh` (`$GITROOT` is obtained via `git rev-parse --show-toplevel`)
* `PENRUN_USER_CONF`: `$HOME/.config/penrun/config.sh`
* `PENRUN_GLOBAL_CONF: ``/etc/penrun/config.sh`

If **one** of these files is found, automatic sourcing of config files stops.
This choice was made in order to avoid confusing about old and forgotten config files.
Config loading has to be explicit.
If a config hierarchy is required a snippet like the following could be placed in the configuration:

----
# stuff …

if [[ -n "${PENRUN_GLOBAL_CONF-}" ]]; then
    source "$PENRUN_GLOBAL_CONF"
fi
----

If one of these variables (`PENRUN_PWD_CONF`, …) is not defined, then the config file does not exist.

=== Variables

The following variables have special meaning in a penrun(1) config script.

DEFAULT_ARGS (array)::
    These arguments are prepended to the arguments of SHELLCOMMAND.
    If SHELLCOMMAND is `ls -lah` and DEFAULT_ARGS is `(--foo --bar)`, then the following command is invoked: `ls --foo --bar -lah`.

=== Hooks

Hook functions can be defined as ordinary shell functions.
The hooks are executed in `artifactsdir`.
The following hooks are available:

`pre_run`::
    This function is run **before** SHELLCOMMAND.

`post_run`::
    This function is run **after** SHELLCOMMAND.

== Artifacts

On each invocation a new directory is created at the following location `$PWD/$SHELLCOMMAND/run-$(date +%Y%m%d-%H%M%S)`, called `artifactsdir`.
Before SHELLCOMMAND is invoked, the current directory is changed to `artifactsdir`.
Artifacts, such as pcap or penlog files, can easily be placed in the current working directory of SHELLCOMMAND.
The output of stderr and stdout is stored in a file `OUTPUT` in the `artifactsdir`.
Metainformation, such as the exit code, are placed in a file `META` in the `artifactsdir`.
The environment is stored in a file `ENV` in the `artifactsdir`.
In order to locate the last run, the last run's `artifactsdir` is always symlinked with `LATEST`.

=== META

META files contain metainformation about the respective testrun for reproducability reasons.
The file format is a simple linebased key value format.
Keys are separated from values with a colon `:`; whitespace has no semantic meaning.
META files contain the following key value pairs:

COMMAND (string)::
    The full invocation string; in this manpage referred to as SHELLCOMMAND.

EXIT (integer)::
    The exit code of the issued SHELLCOMMAND.

START (string)::
    The exact start date of SHELLCOMMAND in ISO8601 format.

END (string)::
    The exact end date of SHELLCOMMAND in ISO8601 format.

=== ENV

All environment variables are stored in this file.
The format is the same as produced by the `printenv` tool.

=== OUTPUT

OUTPUT files contain the unfiltered stderr and stdout of SHELLCOMMAND.
It may be compressed which is then indicated with a `.gz` or `.zst` file extension.

If hooks are run, their output is stored in PRERUN_OUTPUT and POSTRUN_OUTPUT.

== Examples

    $ penrun ls -lah > /dev/null
    $ penrun ls -lah > /dev/null
    $ tree ls
    ls
    ├── LATEST -> run-20200710-101415
    ├── run-20200710-101334
    │   ├── ENV
    │   ├── META
    │   └── OUTPUT
    └── run-20200710-101415
        ├── ENV
        ├── META
        └── OUTPUT

== Environment Variables

PENRUN_NO_CAPTURE::
    If this variable is set to a non empty value, do not create an OUTPUT file, since the user knows better.

PENRUN_NO_HOOK_CAPTURE::
    If this variable is set to a non empty value, do not create PRERUN_OUTPUT and POSTRUN_OUTPUT files, since the user knows better.

== See Also

hr(1), penlog(7), penlog-pest-practice(7)

include::footer.adoc[]
