name: "conventional-commits"

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commits
        uses: crqra/conventional-commits-action@1.0.0
